config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }

  devise_for :end_users, controllers: {
  sessions:      'end_users/sessions',
  passwords:     'end_users/passwords',
  registrations: 'end_users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'end_users/confirm' => 'end_users#confirm'
    patch 'end_users/unsubscribe' => 'end_users#unsubscribe'
    get 'end_users/favorite_list' => 'end_users#favorite_list'
    resources :end_users, only:[:show, :edit, :update]
    resources :musician_profiles, except:[:destroy] do
      resources :musician_reviews, only:[:index, :create, :show]
      resource :musician_favorites, only:[:create, :destroy]
    end
    resources :shop_profiles, except:[:destroy] do
      resources :shop_reviews, only:[:index, :create, :show]
      resource :shop_favorites, only:[:create, :destroy]
    end
    post 'contacts/confirm' => 'contacts#confirm'
    post 'contacts/back' => 'contacts#back'
    get 'contacts/thanks' => 'contacts#thanks'
    resources :contacts, only:[:new, :create]
    resources :rooms, only:[:new, :index, :create, :destroy] do
      resources :messages
    end
    resources :notifications, only:[:index]
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :musician_profiles, only:[:show, :index, :edit, :update] do
      resources :musician_reviews, only:[:index]
    end
    resources :shop_profiles, only:[:show, :index, :edit, :update] do
      resources :shop_reviews, only:[:index]
    end
    resources :end_users, only:[:show, :edit, :update]
    resources :contacts, except:[:show, :create, :new]
  end
end

app/models/musician_profile.rb
class MusicianProfile < ApplicationRecord
  has_one_attached :video
  attachment :image
  belongs_to :end_user
  has_many :musician_reviews, dependent: :destroy
  has_many :musician_favorites, dependent: :destroy

  enum area: {hokkaido:0,aomori:1,iwate:2,miyagi:3,akita:4,yamagata:5,fukushima:6,
     ibaraki:7,tochigi:8,gunma:9,saitama:10,chiba:11,tokyo:12,kanagawa:13,nigata:14,
     toyama:15,ishikawa:16,fukui:17,yamanashi:18,nagano:19,gifu:20,shizuoka:21,aichi:22,
     mie:23,shiga:24,kyoto:25,osaka:26,hyogo:27,nara:28,wakayama:29,tottori:30,
     shimane:31,okayama:32,hiroshima:33,yamaguchi:34,tokushima:35,kagawa:36,ehime:37,kochi:38,
     fukuoka:39,saga:40,nagasaki:41,kumamoto:42,oita:43,miyazaki:44,kagoshima:45, okinawa:46}

  enum genre: {pops:0, rock:1, electronica:2, hiphop:3, raggae:4, r_and_b:5,
  country:6, world:7, enka:8, japanese_old_pops:9, jazz:10, classic:11, others:12}

  #scope :get_by_genre, ->(genre,area) {where(genre: genre).where(area: area)}

  scope :search, -> (genre:, area:, username:) do

    return self if genre.blank? && area.blank? && username.blank?

    if genre.blank?
      if area.blank?
        self.joins(:end_user).where(" (end_users.username LIKE ?)", "%#{username}%").select("musician_profiles.*, end_users.username")
      else
        self.joins(:end_user).where(" (area = ?) AND (end_users.username LIKE ?)", MusicianProfile.areas[area], "%#{username}%").select("musician_profiles.*, end_users.username")
      end
    elsif area.blank?
      if genre.blank?
        self.joins(:end_user).where(" (end_users.username LIKE ?)", "%#{username}%").select("musician_profiles.*, end_users.username")
      else
        self.joins(:end_user).where("(genre = ?) AND (end_users.username LIKE ?)", MusicianProfile.genres[genre], "%#{username}%").select("musician_profiles.*, end_users.username")
      end
    elsif username.blank?
      self.joins(:end_user).where("(genre = ?) AND (area = ?)", MusicianProfile.genres[genre], MusicianProfile.areas[area]).select("musician_profiles.*, end_users.username")
    else
      self.joins(:end_user).where(" (genre = ? ) AND (area = ?) AND (end_users.username LIKE ?)", MusicianProfile.genres[genre], MusicianProfile.areas[area], "%#{username}%").select("musician_profiles.*, end_users.username")
    end
  end

  scope :get_genre, -> (genre) { joins(:end_user).where(genre: genre) if genre.present? }
  scope :get_area, -> (area) { where(area: area) if area.present? }

  validates :area, presence: true
  validates :genre, presence: true
  validates :instrument, presence: true
  validates :total_member, presence: true
  validates :introduction, length: {maximum: 250}
end

app/controllers/admin/musician_profiles_controller.rb
class Admin::MusicianProfilesController < ApplicationController

  def show
    @musician_profile = MusicianProfile.find(params[:id])
    @end_user = @musician_profile.end_user
    @musician_reviews = MusicianReview.where(musician_profile_id: params[:id])
  end

  def index
    @musician_profiles = MusicianProfile.all
  end

  def edit
    @musician_profile = MusicianProfile.find(params[:id])
  end

  def update
    @musician_profile = MusicianProfile.find(params[:id])
    if @musician_profile.update(musician_profile_params)
      redirect_to admin_musician_profile_path(@musician_profile.id)
    else
      render :edit
    end
  end

  private

  def musician_profile_params
    params.require(:musician_profile).permit(:genre, :end_user_id, :review_id, :area, :instrument, :total_member, :is_vocal, :video, :introduction, :price, :rate, :image)
  end

end

app/helpers/admin/musician_profiles_helper.rb
module Admin::MusicianProfilesHelper
end

app/views/admin/musician_profiles/edit.html.erb
<div class="container">
  <h1 class="musician-profile-heading">Edit Profile</h1><br><br>
  <div class="row justify-content-center">
    <%= form_with model: @musician_profile, url:admin_musician_profile_path(@musician_profile.id), local:true do |f| %>

    <div class="form-group">
      <%= f.label :image, "プロフィール画像" %><br>
      <%= f.attachment_field :image %>
    </div>
    <div class="form-group">
      <%= f.label :area, "活動エリア" %>
      <%= f.select :area, MusicianProfile.areas_i18n.invert, {prompt: "---"}, {class:"form-control"} %>
    </div>
    <div class="form-group">
      <%= f.label :genre, "音楽ジャンル" %>
      <%= f.select :genre, MusicianProfile.genres_i18n.invert, {prompt: "---"}, {class:"form-control"} %>
    </div>
    <div class="form-group">
      <%= f.label :instrument, "楽器" %>
      <%= f.text_field :instrument, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :total_member, "活動人数" %>
      <div class="d-flex flex-row">
        <%= f.text_field :total_member, class:"form-control" %><span> 人</span>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :is_vocal, "ボーカルの有無" %>
      <%= f.radio_button :is_vocal, :有り, checked: "checked" %>
      <%= f.label :有り %>
      <%= f.radio_button :is_vocal, :無し %>
      <%= f.label :無し %>
    </div>
    <div class="form-group">
      <%= f.label :video_id, "演奏動画" %><br>
      <%= f.file_field :video %>
    </div>
    <div class="form-group">
      <%= f.label :introduction, "自己紹介文" %>
      <%= f.text_area :introduction, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :price, "希望価格/1時間" %>
      <div class="d-flex flex-row">
        <%= f.text_field :price, class:"form-control" %><span> 円</span>
      </div>
    </div>
    <br>
    <%= f.submit "変更", class:"btn btn-outline-success btn-block" %>
    <% end %>
  </div>
</div>

app/views/admin/musician_profiles/index.html.erb
<div class="container">
  <h1 class="musician-profile-heading">Musicians</h1>
    <div class="row">
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>ユーザーネーム</th>
            <th>エリア</th>
            <th>楽器</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @musician_profiles.each do |musician_profile| %>
            <tr>
              <td><%= attachment_image_tag musician_profile, :image, :fill, 100, 100, fallback:"no_image.jpg", size:"100x100" %></td>
              <td><%= musician_profile.end_user.username.truncate(10) %></td>
              <td><%= musician_profile.area_i18n %></td>
              <td><%= musician_profile.instrument.truncate(10) %></td>
              <td><%= link_to "詳細",admin_musician_profile_path(musician_profile.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/admin/musician_profiles/show.html.erb
<div class="container">
  <h1 class="musician-profile-heading">Profile</h1>
    <div class="row">
      <div class="col-6">
        <%= attachment_image_tag @musician_profile, :image, :fill, 320, 250, fallback:"no_image.jpg", size:"320x250", class:"shop-icon" %>
          <div id="avarage"></div>
          <p class="review-count"><%= link_to @musician_reviews.count, musician_profile_musician_reviews_path(musician_profile_id: @musician_profile.id) %>件のレビュー</p>
      </div>
      <div class="col-6">
        <p class="profile-name"><%= @musician_profile.end_user.username %></p>
      </div>
    </div>
    <br><br>
    <div class="row">
      <div class="profile-box col-12">
        <strong class="profile-label">音楽ジャンル</strong>
        <p><%= @musician_profile.genre_i18n %></p>
        <strong class="profile-label">活動エリア</strong>
        <p><%= @musician_profile.area_i18n %></p>
        <strong class="profile-label">楽器</strong>
        <p><%= @musician_profile.instrument %></p>
        <strong class="profile-label">活動人数</strong>
        <p><%= @musician_profile.total_member %>人</p>
        <strong class="profile-label">ボーカルの有無</strong>
        <% if @musician_profile.is_vocal = true %>
          <p>有り</p>
        <% else %>
          <p>無し</p>
        <% end %>
        <strong class="profile-label">希望価格/1時間</strong>
        <p><%= @musician_profile.price %></p>
        <strong class="profile-label">自己紹介文</strong>
        <p class="profile-sentence"><%= @musician_profile.introduction %></p>
        <strong class="profile-label">演奏動画</strong><br>
        <% if @musician_profile.video.attached? %>
          <video src="<%= rails_blob_path(@musician_profile.video) %>" type="video/mp4" controls></video>
        <% end %>
      </div>
    </div>
    <br>
    <div class="row">
      <%= link_to "編集", edit_admin_musician_profile_path(@musician_profile.id), class:"btn btn-outline-success mx-auto" %>
      <%= link_to "会員情報",admin_end_user_path(@end_user.id), class:"btn btn-outline-dark mx-auto" %>
    </div>
</div>

<script>
  <% @musician_reviews = MusicianReview.where(musician_profile_id: params[:id]) %>
  <% if @musician_reviews == [] %>
    <% review_average = 0 %>
  <% else %>
    <% review_average = @musician_reviews.average(:rate).round(1) %>
  <% end %>
  $('#star').raty({
    size: 36,
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    scoreName: 'musician_review[rate]',
    half: true
  });
  $('#avarage').raty({
    size: 36,
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    scoreName: 'musician_review[rate]',
    half: true,
    readOnly: true,
    score: "<%= review_average %>"
  });
</script>