config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }

  devise_for :end_users, controllers: {
  sessions:      'end_users/sessions',
  passwords:     'end_users/passwords',
  registrations: 'end_users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'end_users/confirm' => 'end_users#confirm'
    patch 'end_users/unsubscribe' => 'end_users#unsubscribe'
    get 'end_users/favorite_list' => 'end_users#favorite_list'
    resources :end_users, only:[:show, :edit, :update]
    resources :musician_profiles, except:[:destroy] do
      resources :musician_reviews, only:[:index, :create, :show]
      resource :musician_favorites, only:[:create, :destroy]
    end
    resources :shop_profiles, except:[:destroy] do
      resources :shop_reviews, only:[:index, :create, :show]
      resource :shop_favorites, only:[:create, :destroy]
    end
    post 'contacts/confirm' => 'contacts#confirm'
    post 'contacts/back' => 'contacts#back'
    get 'contacts/thanks' => 'contacts#thanks'
    resources :contacts, only:[:new, :create]
    resources :rooms, only:[:new, :index, :create, :destroy] do
      resources :messages
    end
    resources :notifications, only:[:index]
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :musician_profiles, only:[:show, :index, :edit, :update] do
      resources :musician_reviews, only:[:index]
    end
    resources :shop_profiles, only:[:show, :index, :edit, :update] do
      resources :shop_reviews, only:[:index]
    end
    resources :end_users, only:[:show, :edit, :update]
    resources :contacts, except:[:show, :create, :new]
  end
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :musician_profile, dependent: :destroy
  has_one :shop_profile, dependent: :destroy
  has_many :musician_reviews, dependent: :destroy
  has_many :shop_reviews, dependent: :destroy
  has_many :musician_favorites, dependent: :destroy
  has_many :shop_favorites, dependent: :destroy
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  has_many :notifications, dependent: :destroy

  def already_musician_favorited?(musician_profile)
    self.musician_favorites.exists?(musician_profile_id: musician_profile.id)
  end

  def already_shop_favorited?(shop_profile)
    self.shop_favorites.exists?(shop_profile_id: shop_profile.id)
  end
  enum end_user_status: {musician:1, shop:2}

  validates :username, length: {maximum: 20}
  validates :name, presence: true
end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController

  def index
    @end_users = EndUser.all
  end

  def show
    @end_user = EndUser.find(params[:id])
  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
    @end_user = EndUser.find(params[:id])
    if @end_user.update(end_user_params)
      redirect_to admin_end_user_path(@end_user.id)
    else
      render :edit
    end
  end

  private

  def end_user_params
    params.require(:end_user).permit(:name,:is_active,:end_user_status)
  end
end

app/controllers/end_users/confirmations_controller.rb
# frozen_string_literal: true

class EndUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/end_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class EndUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/end_users/passwords_controller.rb
# frozen_string_literal: true

class EndUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/end_users/registrations_controller.rb
# frozen_string_literal: true

class EndUsers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  def after_sign_up_path_for(resource)
  # def after_inactive_sign_up_path_for(resource)
    case resource.end_user_status
    when "musician"
      new_musician_profile_path(resource)
    when "shop"
      new_shop_profile_path(resource)
    end
  end

end

app/controllers/end_users/sessions_controller.rb
# frozen_string_literal: true

class EndUsers::SessionsController < Devise::SessionsController
  before_action :reject_inactive_end_user, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_inactive_end_user
    @end_user = EndUser.find_by(email: params[:end_user][:email])
    if @end_user
      if @end_user.valid_password?(params[:end_user][:password]) && !@end_user.is_active
        redirect_to new_end_user_session_path
      end
    end
  end

end

app/controllers/end_users/unlocks_controller.rb
# frozen_string_literal: true

class EndUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/views/admin/end_users/edit.html.erb
<div class="container">
  <h1 class="end-user-heading">Edit User's Infomation</h1><br><br>
    <div class="row justify-content-center">
      <%= form_with model: @end_user, url:admin_end_user_path(@end_user.id), local: true do |f| %>

      <div class="form-group">
        <%= f.label :name, "氏名" %>
        <%= f.text_field :name, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :username, "ユーザーネーム" %>
        <%= f.text_field :username, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email, "メールアドレス" %>
        <%= f.email_field :email, class:"form-control" %>
      </div>
      <br>
      <div class="form-group">
        <%= f.label :end_user_status, "会員タイプ選択" %>
        <%= f.radio_button :end_user_status, :musician %>
        <%= f.label :ミュージシャン %>
        <%= f.radio_button :end_user_status, :shop %>
        <%= f.label :お店 %>
      </div>
      <br>
      <div class="form-group">
        <%= f.label :is_active, "会員ステータス" %>
        <%= f.radio_button :is_active, "有効", checked: "checked" %>
        <%= f.label :有効 %>
        <%= f.radio_button :is_active, "退会" %>
        <%= f.label :退会 %>
      </div>
      <br>
      <%= f.submit "変更", class:"btn btn-outline-success btn-block" %>
      <% end %>
    </div>
    <br>
    <br>
    <div class="row justify-content-center">
      <p>退会は<%= link_to "こちら", end_users_confirm_path %></p>
    </div>
</div>

app/views/admin/end_users/show.html.erb
<div class="container">
  <h1 class="end-user-heading">User's infomation</h1>
  <div class="row">
    <table class="table">
      <tr>
        <th>氏名</th>
        <td><%= @end_user.name %></td>
      </tr>
      <tr>
        <th>ユーザーネーム</th>
        <td><%= @end_user.username.truncate(20) %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @end_user.email %></td>
      </tr>
      <tr>
        <th>会員タイプ</th>
        <td>
          <% if @end_user.end_user_status == "musician" %>
            <p>ミュージシャン</p>
          <% else %>
            <p>お店</p>
          <% end %>
        </td>
      </tr>
      <tr>
        <th>プロフィール</th>
        <td>
          <% if @end_user.musician? %>
          <%= link_to "表示", admin_musician_profile_path(@end_user.musician_profile.id), class:"btn btn-outline-dark" %>
          <% end %>
          <% if @end_user.shop? %>
          <%= link_to "表示", admin_shop_profile_path(@end_user.shop_profile.id), class:"btn btn-outline-dark" %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th>会員情報</th>
        <td><%= link_to "編集", edit_admin_end_user_path(@end_user.id), class:"btn btn-outline-dark" %></td>
      </tr>
      <tr>
        <th>会員ステータス</th>
        <td>
          <% if @end_user.is_active == true %>
            <p>有効</p>
          <% else %>
            <p>退会</p>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
</div>