config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }

  devise_for :end_users, controllers: {
  sessions:      'end_users/sessions',
  passwords:     'end_users/passwords',
  registrations: 'end_users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'end_users/confirm' => 'end_users#confirm'
    patch 'end_users/unsubscribe' => 'end_users#unsubscribe'
    get 'end_users/favorite_list' => 'end_users#favorite_list'
    resources :end_users, only:[:show, :edit, :update]
    resources :musician_profiles, except:[:destroy] do
      resources :musician_reviews, only:[:index, :create, :show]
      resource :musician_favorites, only:[:create, :destroy]
    end
    resources :shop_profiles, except:[:destroy] do
      resources :shop_reviews, only:[:index, :create, :show]
      resource :shop_favorites, only:[:create, :destroy]
    end
    post 'contacts/confirm' => 'contacts#confirm'
    post 'contacts/back' => 'contacts#back'
    get 'contacts/thanks' => 'contacts#thanks'
    resources :contacts, only:[:new, :create]
    resources :rooms, only:[:new, :index, :create, :destroy] do
      resources :messages
    end
    resources :notifications, only:[:index]
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :musician_profiles, only:[:show, :index, :edit, :update] do
      resources :musician_reviews, only:[:index]
    end
    resources :shop_profiles, only:[:show, :index, :edit, :update] do
      resources :shop_reviews, only:[:index]
    end
    resources :end_users, only:[:show, :edit, :update]
    resources :contacts, except:[:show, :create, :new]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoundLodge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/f6d278026b.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= link_to image_tag("logo.jpg"), "/",class: "navbar-brand" %>
      <% if @notification_message.present? %>
        <%= link_to rooms_path do %>
          <i class="far fa-envelope fa-lg"></i>
        <% end %>
      <% end %>
      <% if @notification_review.present? %>
        <% if current_end_user.end_user_status == "musician" %>
          <%= link_to musician_profile_musician_reviews_path(musician_profile_id: current_end_user.musician_profile.id) do %>
            <i class="notification far fa-star fa-lg"></i>
          <% end %>
        <% else %>
          <%= link_to shop_profile_shop_reviews_path(shop_profile_id: current_end_user.shop_profile.id) do %>
            <i class="notification far fa-star fa-lg"></i>
          <% end %>
        <% end %>
      <% end %>
      <% if @notification_favorite.present? %>
        <% if current_end_user.end_user_status == "musician" %>
          <%= link_to musician_profile_path(current_end_user.musician_profile.id) do %>
          <i class="fas fa-heart"></i>
          <% end %>
        <% else %>
          <%= link_to shop_profile_path(current_end_user.shop_profile.id) do %>
            <i class="fas fa-heart"></i>
          <% end %>
        <% end %>
      <% end %>
      <div id="sp-menu">
        <ul class="nav-content">
          <% if end_user_signed_in? %>
            <li class="nav-list"><%= link_to 'ホーム', root_path, class:"nav-link" %></li>
            <li class="nav-list"><%= link_to 'Sound Lodgeとは', about_path, class:"nav-link" %></li>
            <li class="nav-list"><%= link_to 'マイページ', end_user_path(current_end_user.id), class:"nav-link" %></li>
            <li class="nav-list"><%= link_to 'お店を探す', shop_profiles_path, class:"nav-link" %></li>
            <li class="nav-list"><%= link_to 'ミュージシャンを探す', musician_profiles_path, class:"nav-link" %></li>
            <li class="nav-list"><%= link_to 'お問い合わせ', new_contact_path, class:"nav-link" %></li>
            <li class="nav-list"><%= link_to 'ログアウト', destroy_end_user_session_path, method: :delete, class:"nav-link" %></li>
          <% elsif admin_signed_in? %>
            <li class="nav-list"><%= link_to '会員店舗一覧', admin_shop_profiles_path, class:"nav-link" %></li>
            <li class="nav-list"><%= link_to '会員ミュージシャン一覧', admin_musician_profiles_path, class:"nav-link" %> </li>
            <li class="nav-list"><%= link_to 'お問い合わせ一覧', admin_contacts_path, class:"nav-link" %></li>
            <li class="nav-list"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class:"nav-link" %></li>
          <% else %>
            <li class="nav-list"><%= link_to 'ホーム', root_path, class:"nav-link" %></li>
            <li class="nav-list"><%= link_to 'Sound Lodgeとは', about_path, class:"nav-link" %></li>
            <li class="nav-list"><%= link_to 'ログイン', new_end_user_session_path, class:"nav-link" %></li>
            <li class="nav-list"><%= link_to 'お店を探す', shop_profiles_path, class:"nav-link" %></li>
            <li class="nav-list"><%= link_to 'ミュージシャンを探す', musician_profiles_path, class:"nav-link" %></li>
            <li class="nav-list"><%= link_to 'お問い合わせ', new_contact_path, class:"nav-link" %></li>
          <% end %>
        </ul>
      </div>
      <div id="hm-icon">
        <a class="menu-trigger" href="#">
          <span></span>
          <span></span>
          <span></span>
        </a>
    </div>
    </header>
    <%= yield %>
    <footer>
      <div class="container text-center">
        <ul class="nav justify-content-center">
          <li class="nav-item"><%= link_to "Home", root_path, class:"footer-link" %></li>
          <li class="nav-item"><%=link_to "About", about_path, class:"footer-link" %></li>
          <li class="nav-item"><%= link_to "お問い合わせ", new_contact_path, class:"footer-link" %></li>
        </ul>
      </div>
    </footer>
  </body>
</html>